modLoader="javafml"
loaderVersion="[32,)" # 1.16+
license="LGPL v3.0"
issueTrackerURL="https://github.com/PieKing1215/WaterDripSound/issues"
[[mods]]
modId="waterdripsound"
version="0.3.0"
displayName="Drip Sounds"
displayURL="https://github.com/PieKing1215/WaterDripSound"
logoFile="logo.png"
authors="PieKing1215"
description='''Makes drip particles play a sound (and other related changes).'''

[[dependencies.waterdripsound]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.waterdripsound]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.waterdripsound]]
    modId="cloth-config"
    mandatory=true
    versionRange="[4.0,)"
    ordering="NONE"
    side="CLIENT"
