modLoader="javafml" #mandatory
loaderVersion="[32,)"
license="GPL v3.0"
issueTrackerURL="https://github.com/PieKing1215/WaterDripSound/issues" #optional
[[mods]]
modId="waterdripsound"
version="0.1.3"
displayName="Water Drip Sound"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/PieKing1215/WaterDripSound"
logoFile="logo.png"
#credits=""
authors="PieKing1215"
description='''
Makes water drips play a sound.
'''

[[dependencies.waterdripsound]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[32,)" #mandatory
    ordering="NONE"
    side="BOTH"
# Here's another dependency
[[dependencies.waterdripsound]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
[[dependencies.waterdripsound]]
    modId="cloth-config"
    mandatory=true
    versionRange="[4.0,)"
    ordering="NONE"
    side="CLIENT"
